# Generated by Django 5.1 on 2025-05-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_answer_options_alter_element_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('solved_elements', models.JSONField(default=dict)),
                ('current_theme', models.CharField(blank=True, max_length=100, null=True)),
                ('score', models.IntegerField(default=0)),
                ('lives', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'chatbot_usergamesession',
            },
        ),
    ]
