# Generated by Django 5.1 on 2025-05-01 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_usergamesession'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='answer',
            name='element',
        ),
        migrations.AlterUniqueTogether(
            name='element',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='element',
            name='room',
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='room',
            name='theme',
        ),
        migrations.DeleteModel(
            name='UserGameSession',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Element',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
    ]
